// jarboot-ui/src/components/servers/view/HeapDumpView.tsx
import React, {memo} from "react";
import {Result, Button} from "antd";
import {DownloadOutlined} from '@ant-design/icons';
import CommonUtils from "@/common/CommonUtils";
import StringUtil from "@/common/StringUtil";

const HeapDumpView = memo((props: any) => {
    const token = CommonUtils.getRawToken();
    const {data, remote} = props;
    let subTitle = data?.dumpFile;
    const isRemote = (StringUtil.isNotEmpty(remote) && 'localhost' !== remote && '127.0.0.1' !== remote);
    if (isRemote) {
        subTitle = `Dump file is stored in remote server ${remote}, can't download directly.`;
    }
    return <>
        <Result
            status="success"
            title="Heap dump success!"
            subTitle={subTitle}
            extra={[
                <Button icon={<DownloadOutlined/>}
                        type="primary"
                        disabled={isRemote}
                        key="Download"
                        href={`/api/jarboot/cloud/download/${data?.encodedName}?${CommonUtils.ACCESS_TOKEN}=${token}`}>
                    Download
                </Button>
            ]}/>
    </>;
});

export default HeapDumpView;

// jarboot-ui2/src/components/super-panel/heapdump-view.vue
<template>
  <div>
    <el-result icon="success" title="Heap dump success!" :sub-title="subTitle">
      <template #extra>
        <el-button type="primary" icon="Download" @click="download">{{ $t('DOWNLOAD') }}</el-button>
      </template>
    </el-result>
  </div>
</template>

<script setup lang="ts">
import CommonUtils from '@/common/CommonUtils';
import StringUtil from '@/common/StringUtil';

const props = defineProps<{
  data: any;
  remote: string;
}>();

const token = CommonUtils.getRawToken();
let subTitle = props.data?.dumpFile;
const isRemote = StringUtil.isNotEmpty(props.remote) && 'localhost' !== props.remote && '127.0.0.1' !== props.remote;
if (isRemote) {
  subTitle = `Dump file is stored in remote server ${props.remote}, can't download directly.`;
}
function download() {
  const url = `/api/jarboot/cloud/download/${props.data?.encodedName}?${CommonUtils.ACCESS_TOKEN}=${token}`;
  CommonUtils.download(url, 'heapdump.hprof');
}
</script>

<style scoped></style>
