// jarboot-ui2/src/components/super-panel/DashboardView.vue
<template>
  <el-tabs v-model="state.tab">
    <el-tab-pane label="概览" name="overview">
      <el-row>
        <el-col :span="12">
          <div ref="threadChartRef" :style="{width: '100%', height: (viewHeight / 2) + 'px'}"></div>
        </el-col>
        <el-col :span="12">
          堆内存趋势
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="12">
          线程趋势
        </el-col>
        <el-col :span="12">
          堆内存趋势
        </el-col>
      </el-row>
    </el-tab-pane>
    <el-tab-pane label="线程" name="threads">
      <el-table :data="props.data.threads" style="width: 100%" :height="viewHeight" size="small" stripe>
        <el-table-column prop="id" label="ID" width="60" />
        <el-table-column prop="name" label="NAME" :show-overflow-tooltip="true"/>
        <el-table-column prop="group" label="GROUP" width="80" :show-overflow-tooltip="true"/>
        <el-table-column prop="priority" label="PRIORITY" width="80" />
        <el-table-column prop="state" label="STATE" width="130">
          <template #default="scope">
            <span :style="{color: stateColor(scope.row?.state)}">{{scope.row?.state || '-'}}</span>
          </template>
        </el-table-column>
        <el-table-column prop="cpu" label="%CPU" width="60">
          <template #default="scope">
            <span :style="{color: cpuColorFormat(scope.row?.cpu)}">{{scope.row?.cpu || '0'}}</span>
          </template>
        </el-table-column>
        <el-table-column prop="deltaTime" label="DELTA_TIME" width="100" />
        <el-table-column prop="time" label="TIME" width="60" />
        <el-table-column prop="interrupted" label="INTERRUPTED" width="120" />
        <el-table-column prop="daemon" label="DAEMON" width="100" />
      </el-table>
    </el-tab-pane>
    <el-tab-pane label="内存" name="third">

    </el-tab-pane>
    <el-tab-pane label="系统" name="system">

    </el-tab-pane>
  </el-tabs>
</template>

<script lang="ts" setup>
import * as echarts from "echarts";
import type {EChartsType, EChartsOption} from "echarts";
import {nextTick, reactive, watch, onMounted, computed, ref} from "vue";
import {useDark} from "@vueuse/core";

const isDark = useDark();
const props = defineProps<{
  data: any;
  height: number;
  width: number;
}>();
const viewHeight = computed(() => props.height - 30);
const state = reactive({
  tab: 'overview',
  history: [] as any[],
});
const threadChartRef = ref();
const MAX_RECORD = 100;

let threadChart = null as unknown as EChartsType;

const resizeChart = () => {
  threadChart?.resize();
};

watch(() => props.data, (newData: any) => {
  state.history.push({...newData});
  if (state.history.length > MAX_RECORD) {
    state.history.shift();
  }
  nextTick(updateChart);
});
watch(() => props.height, resizeChart);
watch(() => props.width, resizeChart);

const updateThreadChart = () => {
  const his = [...state.history];
    const NEW = {
      name: 'NEW',
      type: 'line',
      smooth: true,
      data: []
    };
    const RUNNABLE = {
      name: 'RUNNABLE',
      type: 'line',
      smooth: true,
      data: []
    };
    const BLOCKED = {
      name: 'BLOCKED',
      type: 'line',
      smooth: true,
      data: []
    };
    const WAITING = {
      name: 'WAITING',
      type: 'line',
      smooth: true,
      data: []
    };
    const TIMED_WAITING = {
      name: 'TIMED_WAITING',
      type: 'line',
      smooth: true,
      data: []
    };
    const TERMINATED = {
      name: 'TERMINATED',
      type: 'line',
      smooth: true,
      data: []
    };

  const total = {
    name: 'total',
    type: 'line',
    smooth: true,
    data: [] as any[]
  };
  const map = {NEW, RUNNABLE, BLOCKED, WAITING, TIMED_WAITING, TERMINATED} as any;
  const states = ['NEW', 'RUNNABLE', 'BLOCKED', 'WAITING', 'TIMED_WAITING', 'TERMINATED'];
  const xData = [] as string[];
  his.slice(-20).forEach((item: any) => {
    const timestamp = item.runtimeInfo.timestamp;
    const date = new Date(timestamp);
    states.forEach(state => {
      const count = (item.threads || []).filter((thread: any) => state === thread.state).length;
      map[state].data.push({
        name: date.toString(),
        value: [
          date,
          count
        ]
      });
    });
    total.data.push({
      name: date.toString(),
      value: [
        date,
        (item.threads as any[]).length
      ]
    });
    xData.push(`${date.getHours()}:${date.getMinutes()} ${date.getSeconds()}`);
  });

  const option: EChartsOption = {
    title: {
      text: 'Thread'
    },
    darkMode: isDark.value,
    tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'cross',
        label: {
          backgroundColor: '#6a7985'
        }
      }
    },
    xAxis: {
      type: 'time',
      splitLine: {
        show: false
      }
    },
    yAxis: {
      type: 'value',
      boundaryGap: [0, '100%'],
      splitLine: {
        show: false
      }
    },
    series: [/*NEW, */RUNNABLE, BLOCKED, /*WAITING, TIMED_WAITING, TERMINATED,*/ total]
  };
  if (his.length <= 1) {
    threadChart.setOption(option);
  } else {
    threadChart.setOption({
      series: [
        {
          data: RUNNABLE.data
        },
        {
          data: BLOCKED.data
        },
        {
          data: total.data
        }
      ]
    });
  }
};
const updateChart = () => {
  updateThreadChart();
}

onMounted(() => {
  threadChart = echarts.init(threadChartRef.value);
});
const stateColor = (state: any) => {
  let color;
  switch (state) {
    case 'NEW':
      color = "cyan";
      break;
    case 'RUNNABLE':
      color = "green";
      break;
    case 'BLOCKED':
      color = "red";
      break;
    case 'WAITING':
      color = "yellow";
      break;
    case 'TIMED_WAITING':
      color = "magenta";
      break;
    case 'TERMINATED':
      color = "blue";
      break;
    default:
      break;
  }
  return color;
};
const cpuColorFormat = (cpu: number) => {
  let color;
  if (cpu <= 5) {
    color = 'green';
  } else if (cpu > 5 && cpu <= 15) {
    color = 'magenta';
  } else {
    color = 'red';
  }
  return color;
};
</script>

<style lang="less" scoped>

</style>

// jarboot-ui/src/components/servers/view/DashboardView.tsx
import React, {memo} from 'react';
import {Progress, Row, Col, Descriptions} from "antd";
import StringUtil from "@/common/StringUtil";
import styles from "../index.less";
import {JarBootConst} from "@/common/JarBootConst";
import CommonTable from "@/components/table";

const progressValueFormat = (percent: number|undefined) => <span style={{color: percent && percent > 90 ? 'red' : 'green', fontSize: '8px'}}>{percent}%</span>;
const mu = 1024 * 1024;

const cpuColorFormat = (cpu: number) => {
    let color;
    if (cpu <= 5) {
        color = 'green';
    } else if (cpu > 5 && cpu <= 15) {
        color = 'magenta';
    } else {
        color = 'red';
    }
    return <span style={{color}}>{cpu}</span>;
};
const upHeight = (JarBootConst.PANEL_HEIGHT * 0.6);
const downHeight = (JarBootConst.PANEL_HEIGHT * 0.4);

const DashboardView = memo((props: any) => {

    const renderState = (state: any) => {
        if (StringUtil.isEmpty(state)) {
            return '-';
        }
        switch (state) {
            case 'NEW':
                state = <span style={{color: "cyan"}}>{state}</span>;
                break;
            case 'RUNNABLE':
                state = <span style={{color: "green"}}>{state}</span>;
                break;
            case 'BLOCKED':
                state = <span style={{color: "red"}}>{state}</span>;
                break;
            case 'WAITING':
                state = <span style={{color: "yellow"}}>{state}</span>;
                break;
            case 'TIMED_WAITING':
                state = <span style={{color: "magenta"}}>{state}</span>;
                break;
            case 'TERMINATED':
                state = <span style={{color: "blue"}}>{state}</span>;
                break;
            default:
                break;
        }
        return state;
    };
    const getThreadTableProps = () => {
        return {
            columns: [
                {
                    title: 'id',
                    dataIndex: 'id',
                    key: 'id',
                    width: 50,
                },
                {
                    title: 'NAME',
                    dataIndex: 'name',
                    key: 'name',
                    ellipsis: true,
                },
                {
                    title: 'GROUP',
                    dataIndex: 'group',
                    key: 'group',
                    ellipsis: true,
                    render: (text: string) => (StringUtil.isEmpty(text)) ? '-' : text,
                },
                {
                    title: 'PRIORITY',
                    dataIndex: 'priority',
                    key: 'priority',
                },
                {
                    title: 'STATE',
                    dataIndex: 'state',
                    key: 'state',
                    render: renderState,
                },
                {
                    title: '%CPU',
                    dataIndex: 'cpu',
                    key: 'cpu',
                    width: 50,
                    render: cpuColorFormat,
                },
                {
                    title: 'DELTA_TIME',
                    dataIndex: 'deltaTime',
                    key: 'deltaTime',
                },
                {
                    title: 'TIME',
                    dataIndex: 'time',
                    key: 'time',
                },
                {
                    title: 'INTERRUPTED',
                    dataIndex: 'interrupted',
                    key: 'interrupted',
                    render: (interrupted: boolean) => interrupted ? "true" : "false"
                },
                {
                    title: 'DAEMON',
                    dataIndex: 'daemon',
                    key: 'daemon',
                    render: (daemon: boolean) => daemon ? "true" : <span style={{color: 'magenta'}}>false</span>
                },
            ],
            loading: false,
            dataSource: props.data.threads,
            pagination: false,
            //rowKey: 'id',
            size: 'small',
            showHeader: true,
            scroll: upHeight,
        };
    };

    const getMemoryDataSource = () => {
        let data = new Array<any>();
        const memoryInfo: any = props.data.memoryInfo;
        let index = 0;
        for (let key in memoryInfo) {
            if (memoryInfo.hasOwnProperty(key)) {
                const m = memoryInfo[key];
                if (!(m instanceof Array) || m.length <= 0) {
                    continue;
                }
                m.forEach(row => {
                    let item = {id: index++, ...row};
                    data.push(item);
                });
            }
        }
        const gcInfos: any = props.data.gcInfos;
        if (gcInfos instanceof Array && gcInfos.length > 0) {
            index = 0;
            gcInfos.forEach(row => {
                let d = data[index++];
                d['GC'] = `${row.name}.count`;
                d['GCInfo'] = row.collectionCount;
                d = data[index++];
                d['GC'] = `${row.name}.time(ms)`;
                d['GCInfo'] = row.collectionTime;
            })
        }
        return data;
    };

    const getMemoryTableProps = () => {
        return {
            columns: [
                {
                    title: 'NAME',
                    dataIndex: 'name',
                    key: 'name',
                    ellipsis: true,
                },
                {
                    title: 'used(M)',
                    dataIndex: 'used',
                    key: 'used',
                    ellipsis: true,
                    render: (item: any) => (item/mu).toFixed(2)
                },
                {
                    title: 'total(M)',
                    dataIndex: 'total',
                    key: 'total',
                    render: (item: any) => (item/mu).toFixed(2)
                },
                {
                    title: 'max(M)',
                    dataIndex: 'max',
                    key: 'max',
                    render: (item: any) => (item/mu).toFixed(2)
                },
                {
                    title: 'usage',
                    dataIndex: 'usage',
                    key: 'usage',
                    render: (item: any, record: any) => {
                        let percent = (record.used / record.total) * 100;
                        percent = parseFloat(percent.toFixed(2));
                        return <Progress size={"small"}
                                         format={progressValueFormat}
                                         percent={percent}/>
                    }
                },
                {
                    title: 'GC',
                    dataIndex: 'GC',
                    key: 'GC',
                },
                {
                    title: '',
                    dataIndex: 'GCInfo',
                    key: 'GCInfo',
                },
            ],
            loading: false,
            dataSource: getMemoryDataSource(),
            pagination: false,
            rowKey: 'id',
            size: 'small',
            showHeader: true,
            scroll: downHeight,
        };
    };

    let thrTableOption: any = getThreadTableProps();
    thrTableOption.scroll = { y: upHeight};
    let memTableOption: any = getMemoryTableProps();
    memTableOption.scroll = { y: downHeight};
    const runtimeInfo = props?.data?.runtimeInfo;
    return <>
        <div className={styles.smallTable}>
            <CommonTable option={thrTableOption} height={upHeight}/>
            <Row>
                <Col span={16}>
                    <CommonTable option={memTableOption} height={downHeight}/>
                </Col>
                <Col span={8} style={{overflowY: "auto"}}>
                    <Descriptions size={'small'} column={1} bordered>
                        <Descriptions.Item label="os">{runtimeInfo?.osName} {runtimeInfo?.osVersion}</Descriptions.Item>
                        <Descriptions.Item label="average">{runtimeInfo?.systemLoadAverage}</Descriptions.Item>
                        <Descriptions.Item label="processors">{runtimeInfo?.processors}</Descriptions.Item>
                        <Descriptions.Item label="uptime">{runtimeInfo?.uptime}</Descriptions.Item>
                        <Descriptions.Item label="java.version">{runtimeInfo?.javaVersion}</Descriptions.Item>
                        <Descriptions.Item label="java.home" contentStyle={{textOverflow: "ellipsis"}}>{runtimeInfo?.javaHome}</Descriptions.Item>
                    </Descriptions>
                </Col>
            </Row>
        </div>
    </>
});

export default DashboardView;
